### ISSUE TITLE
Waiting for mariadb to be ready in 5 seconds

### ISSUE THREAD

**Issue by ntwrkguru** [openSUSE/docker-containers#43]
Running image from the Docker Hub (tag 2.0) results in an unusable container, waiting on mariadb to be ready.

```
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
 [FAIL]
Timeout reached, exiting with error
```

I'm running it from a playbook; here's the (sanitized) play:
```yaml
  - name: start portus
    docker_container:
      name: portus
      # pull: true
      detach: true
      image: opensuse/portus:2.0
      state: started
      restart_policy: unless-stopped
      volumes:
      - /var/opt/portus/certs/portus-ca.crt:/certificates/portus-ca.crt
      - /var/opt/portus/secrets/portus.key:/secrets/portus.key
      env:
        PORTUS_SECRET_KEY_BASE: xxx
        PORTUS_PORTUS_PASSWORD: xxx
        MARIADB_SERVICE_HOST: localhost
        MARIADB_USER: portus
        MARIADB_PASSWORD: portus
        MARIADB_DATABASE: portus
        PORTUS_MACHINE_FQDN_VALUE: portus.example.com
      published_ports:
      - "80:80"
      - "443:443"
```

Target machine: 
```bash
$ sudo cat /etc/lsb-release  
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Any ideas or tips?
